apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-common-secrets
type: Opaque
data:
  JwtSettings__SecretKey: {{ "your-super-secret-key-minimum-32-characters" | b64enc | quote }}
  # Other shared sensitive config
