---
# This playbook handles the base provisioning of servers
# It installs necessary packages, sets up security, and installs Docker.

- name: Provision All Servers (Common)
  hosts: all
  become: yes
  tags: [common, provision]
  roles:
    - common

- name: Provision Webservers (Docker Application Host)
  hosts: webservers
  become: yes
  tags: [web, provision]
  roles:
    - docker
    # - eks-config # Uncomment if managed via Ansible
