[webservers]
# Local deployment for development
localhost ansible_connection=local

[dbservers]
# Local db for development (if not using docker-compose for db)
localhost ansible_connection=local

[all:vars]
# No need to define env here anymore, it's in group_vars/all.yml
# But we can keep connection specific vars here
ansible_python_interpreter=/usr/bin/python3
