---
# tasks file for docker
- name: Install Docker packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"
  notify: restart docker

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
